name: project
recipe: drupal7

config:
  via: nginx
  xdebug: off
  config:
    php: .lando/php.ini

services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    run_as_root:
      - /app/.lando/adminer.sh
    portforward: true
  appserver:
    type: 'php:7.3'
    webroot: web
    build_as_root:
      - chmod -R a+w /app/web/
    build:
      - composer install
      - /app/.lando/build.sh
    overrides:
      environment:
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"
  database:
    type: 'mariadb:10.3'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    # globals:
    #   gulp-cli: latest

tooling:
  build:
    description: Build an appserver.
    cmd:
      - appserver: /app/.lando/build.sh
  # gulp: 
  #   service: node
  node:
    service: node
  npm:
    service: node
  phpcbf:
    description: Run phpcbf commands.
    cmd:
      - appserver: /app/vendor/bin/phpcbf
  phpcs:
    description: Run phpcs commands.
    cmd:
      - appserver: /app/vendor/bin/phpcs
  syncdb:
    description: Synchronize local database with selected remote environment.
    cmd:
      - appserver: /app/.lando/syncdb.sh
  update:
    description: Apply required (database) updates.
    cmd:
      - appserver: /app/.lando/update.sh
  xdebug:
    description: Loads Xdebug in the selected mode
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root

proxy:
  adminer:
    - adminer-project.lndo.site
  mailhog:
    - mail-project.lndo.site

events:
  post-db-import:
    - appserver: /app/.lando/update.sh

env_file:
  - .lando/lando.env

# Tested with Lando version.
version: v3.0.23
